export const config = {
    isProduction: process.env.NODE_ENV === 'production',
    port: process.env.PORT || 3000,
    issuer: String(process.env.ISSUER),
    dbUserName: String(process.env.DB_USERNAME),
    dbPassword: String(process.env.DB_PASSWORD),
    dbName: String(process.env.DB_NAME),
    dbClusterName: String(process.env.DB_CLUSTER_NAME),
    dbClusterNameSuffix: String(process.env.DB_CLUSTER_NAME_SUFFIX),
    accessTokenExpiresIn: String(process.env.ACCESS_TOKEN_EXPIRES_IN),
    accessTokenSecret: String(process.env.ACCESS_TOKEN_SECRET),
    refreshTokenExpiresIn: String(process.env.REFRESH_TOKEN_EXPIRES_IN),
    refreshTokenSecret: String(process.env.REFRESH_TOKEN_SECRET),
    emailVerificationTokenExpiresIn: String(process.env.EMAIL_VERIFICATION_TOKEN_EXPIRES_IN),
    emailVerificationTokenSecret: String(process.env.EMAIL_VERIFICATION_TOKEN_SECRET),
    forgetPasswordTokenExpiresIn: String(process.env.FORGOT_PASSWORD_TOKEN_EXPIRES_IN),
    forgetPasswordTokenSecret: String(process.env.FORGOT_PASSWORD_TOKEN_SECRET),
    CLOUDINARY_CLOUD_NAME: String(process.env.CLOUDINARY_CLOUD_NAME),
    CLOUDINARY_API_KEY: String(process.env.CLOUDINARY_API_KEY),
    CLOUDINARY_API_SECRET: String(process.env.CLOUDINARY_API_SECRET),
}
