openapi: 3.0.3
info:
  title: ${{title}}
  description: >-
    # ${{description}}
  version: 1.3.1
  contact: {}
servers:
  - url: ${{server}}
paths: 
  /auth/signup:
  post:
    summary: Register new user
    tags:
      - Authentication
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignupRequest'
    responses:
      "201":
        description: OTP sent successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiResponse'


  /auth/verify-email:
    post:
      summary: Verify email using OTP
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        "200":
          description: Email verified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  /auth/resend-otp:
    post:
      summary: Resend email verification OTP
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Email
              properties:
                Email:
                  type: string
                  format: email
                  example: firoz@gmail.com
      responses:
        "200":
          description: OTP sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'


  /auth/login:
    post:
      summary: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Email
                - Password
              properties:
                Email:
                  type: string
                  format: email
                  example: firoz@gmail.com
                Password:
                  type: string
                  format: password
                  example: Password@123
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /auth/forgot-password:
    post:
      summary: Send password reset OTP
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Email
              properties:
                Email:
                  type: string
                  format: email
                  example: firoz@gmail.com
      responses:
        "200":
          description: Password reset OTP sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'


  /auth/reset-password:
    post:
      summary: Reset password using OTP
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Email
                - OTP
                - Password
              properties:
                Email:
                  type: string
                  example: firoz@gmail.com
                OTP:
                  type: string
                  example: "123456"
                Password:
                  type: string
                  format: password
                  example: NewPassword@123
      responses:
        "200":
          description: Password updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'


  /auth/refresh-token:
    post:
      summary: Refresh access token
      tags:
        - Authentication
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI...
      responses:
        "200":
          description: Access token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /auth/me:
    get:
      summary: Get logged in user
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logged in user fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "401":
          description: Unauthorized

  /auth/logout:
    post:
      summary: Logout user
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logged out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "401":
          description: Unauthorized


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        Include your access token as:
        ```
        Authorization: Bearer <access_token>
        ```

  schemas:
    ApiResponse:
      type: object
      properties:
        IsSuccess:
          type: boolean
          example: true
        Message:
          type: string
          example: User registered successfully
        Data:
          nullable: true
          example: null
        Errors:
          type: array
          items:
            type: string
            example: null

    ApiError:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Invalid email or password
        statusCode:
          type: integer
          example: 400
        errors:
          type: array
          items:
            type: string
          example: []

    SignupRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - password
      properties:
        firstName:
          type: string
          example: Firoz
        lastName:
          type: string
          example: Ansari
        email:
          type: string
          format: email
          example: admin@gmail.com
        password:
          type: string
          example: Password@123

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: admin@gmail.com
        password:
          type: string
          example: Password@123
  
    VerifyEmailRequest:
    ServiceRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Web Development
        description:
          type: string
          example: Full stack web application development.
        icon:
          type: string

    ProjectRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        technologies:
          type: array
          items:
            type: string
        projectUrl:
          type: string
        githubUrl:
          type: string
        slug:
          type: string

    ReservedSlugRequest:
      type: object
      required:
        - slug
      properties:
        slug:
          type: string
          example: admin

    LoginResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            Data:
              type: object
              properties:
                accessToken:
                  type: string
                refreshToken:
                  type: string
                user:
                  type: object
                  properties:
                    UniqueCode:
                      type: string
                      example: USR-AB12CD34
                    Name:
                      type: string
                      example: Firoz Ansari
                    Email:
                      type: string
                      example: firoz@gmail.com
                    Role:
                      type: string
                      example: USER